---
extends:
  - airbnb
root: true
parser: "babel-eslint"
env:
  es6: true
  node: true

plugins:
  - promise
  - unicorn

parserOptions:
  sourceType: module

rules:
  unicorn/catch-error-name:
    - error
    - name: err
  unicorn/explicit-length-check: error
  unicorn/filename-case:
    - error
    - case: kebabCase
  unicorn/no-abusive-eslint-disable: error
  unicorn/no-process-exit: error
  unicorn/throw-new-error: error
  unicorn/number-literal-case: error
  unicorn/escape-case: error
  unicorn/no-array-instanceof: error
  unicorn/no-new-buffer: error
  unicorn/no-hex-escape: error
  unicorn/custom-error-definition: error
  unicorn/prefer-starts-ends-with: error
  unicorn/prefer-type-error: error

overrides:
  -
    files:
      - tests/**/*.js
      - benchmark/**/*.js
    rules:
      import/no-extraneous-dependencies:
        - 0
      no-underscore-dangle:
        - 0
      no-console:
        - 0
      no-magic-numbers:
        - 0
      arrow-parens:
        - 0
    env:
      mocha: true
